# Generated by Django 6.0 on 2025-12-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileskill',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='profileskill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
