# Generated by Django 6.0 on 2025-12-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_certification_workload_profilesystem'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='level',
            field=models.CharField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='skills.skill', verbose_name='Habilidade'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Anos de Experiência'),
        ),
        migrations.AlterField(
            model_name='profilesystem',
            name='level',
            field=models.CharField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], max_length=20),
        ),
    ]
