# Generated by Django 6.0 on 2025-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_profileskill_level_alter_profileskill_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileskill',
            name='level',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=1, verbose_name='Nível'),
        ),
    ]
