# Generated by Django 6.0 on 2025-12-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profileskill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Perfil Público'),
        ),
    ]
