# Generated by Django 6.0 on 2025-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesystem',
            name='level',
            field=models.IntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=1, verbose_name='Nível'),
        ),
    ]
