# Generated by Django 6.0 on 2025-12-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_profilesystem_level'),
        ('skills', '0003_alter_skill_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Function', to='skills.function'),
        ),
    ]
