# Generated by Django 6.0 on 2025-12-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='position',
            new_name='function',
        ),
    ]
