# Generated by Django 6.0 on 2025-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_alter_profile_function_alter_profileskill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(default=1, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
