# Generated by Django 6.0 on 2025-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phrase',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Frase de Efeito'),
        ),
        migrations.AlterField(
            model_name='profileskill',
            name='level',
            field=models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=0, verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='profilesystem',
            name='level',
            field=models.IntegerField(choices=[(0, 'Robótico'), (1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado'), (4, 'Especialista')], default=0, verbose_name='Nível'),
        ),
    ]
