# Generated by Django 6.0 on 2025-12-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_function'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
    ]
