# Generated by Django 6.0 on 2025-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_remove_system_owner_sector_function_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['name'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AddField(
            model_name='function',
            name='education_level',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Médio'), ('TECNICO', 'Técnico'), ('SUPERIOR', 'Superior')], default=1, max_length=20, verbose_name='Nível de Escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='function',
            name='workload',
            field=models.PositiveSmallIntegerField(default=1, help_text='Informe a carga horária semanal', verbose_name='Carga Horária (horas/semana)'),
            preserve_default=False,
        ),
    ]
