# Generated by Django 6.0 on 2025-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_function_options_function_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='education_level',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Ensino Fundamental'), ('MEDIO', 'Ensino Médio'), ('TECNICO', 'Ensino Técnico'), ('SUPERIOR', 'Ensino Superior')], max_length=20, verbose_name='Nível de Escolaridade'),
        ),
        migrations.AlterField(
            model_name='function',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Cargo'),
        ),
    ]
