# Generated by Django 6.0 on 2025-12-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_function_education_level_alter_function_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='link',
            field=models.URLField(blank=True, help_text='Link para a lei ou documento oficial que regulamenta o cargo', null=True, verbose_name='Legislação'),
        ),
    ]
