# Generated by Django 6.0 on 2025-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome do Sistema')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('owner_sector', models.CharField(blank=True, max_length=150, verbose_name='Setor Responsável')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], max_length=10)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'unique_together': {('name', 'skill_type')},
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('certification_type', models.CharField(choices=[('technical', 'Curso Técnico'), ('graduation', 'Graduação'), ('postgraduation', 'Pós-graduação'), ('mba', 'MBA'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('postdoctorate', 'Pós-doutorado'), ('course', 'Curso'), ('training', 'Treinamento')], default='course', max_length=20, verbose_name='Tipo de Certificação')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Certificação')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='Arquivo (PDF)')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Certificado')),
                ('skills', models.ManyToManyField(blank=True, related_name='certifications', to='curriculum.skill')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ('-issue_date',),
            },
        ),
    ]
