# Generated by Django 6.0 on 2025-12-09 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('hard', 'Hard Skill'), ('soft', 'Soft Skill')], max_length=10)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'unique_together': {('name', 'skill_type')},
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, to='curriculum.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150, verbose_name='Cargo')),
                ('department', models.CharField(max_length=150, verbose_name='Setor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.talent')),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'verbose_name_plural': 'Experiências Profissionais',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Certificação')),
                ('institution', models.CharField(max_length=200, verbose_name='Instituição')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.talent')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
            },
        ),
        migrations.CreateModel(
            name='TalentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado'), ('expert', 'Especialista')], default='basic', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.skill')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.talent')),
            ],
            options={
                'unique_together': {('talent', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='skills',
            field=models.ManyToManyField(blank=True, through='curriculum.TalentSkill', to='curriculum.skill'),
        ),
    ]
