# Generated by Django 6.0 on 2025-12-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='certification',
            name='workload',
            field=models.PositiveIntegerField(blank=True, help_text='Informe a carga horária total em horas.', null=True, verbose_name='Carga Horária (horas)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='certification_type',
            field=models.CharField(choices=[('technical', 'Curso Técnico'), ('graduation', 'Graduação'), ('postgraduation', 'Pós-graduação'), ('mba', 'MBA'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('postdoctorate', 'Pós-doutorado'), ('course', 'Curso'), ('training', 'Treinamento'), ('workshop-Oficina', 'Workshop/Oficina')], default='course', max_length=20, verbose_name='Tipo de Certificação'),
        ),
    ]
