# Generated by Django 6.0 on 2025-12-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='Arquivo (PDF)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Certificado'),
        ),
    ]
