# Generated by Django 6.0 on 2025-12-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_certification_file_certification_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
