# Generated by Django 6.0 on 2025-12-09 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='categories',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
