# Generated by Django 6.0 on 2025-12-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0001_initial'),
        ('skills', '0006_alter_function_education_level_alter_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to='skills.function', verbose_name='Cargo Efetivo'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Usuario'),
        ),
    ]
